### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by draven72** [googleads/keyword-optimizer#3]
I just cloned the repo and when I ran 'mvn clean install eclipse:eclipse' I got the following error:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[59,17] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
  required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
  found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
  reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[64,16] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
  required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
  found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
  reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[69,21] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
  required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
  found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
  reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[74,17] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
  required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
  found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
  reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[80,21] incompatible types: com.google.api.ads.adwords.axis.v201603.cm.Money cannot be converted to com.google.api.ads.adwords.axis.v201607.cm.Money
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.780 s
[INFO] Finished at: 2016-09-22T15:32:11+01:00
[INFO] Final Memory: 21M/304M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project keyword-optimizer: Compilation failure: Compilation failure:
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[59,17] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
[ERROR] required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
[ERROR] found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[64,16] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
[ERROR] required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
[ERROR] found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[69,21] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
[ERROR] required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
[ERROR] found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[74,17] constructor KeywordInfo in class com.google.api.ads.adwords.keywordoptimizer.KeywordInfo cannot be applied to given types;
[ERROR] required: com.google.api.ads.adwords.axis.v201607.cm.Keyword,com.google.api.ads.adwords.keywordoptimizer.IdeaEstimate,com.google.api.ads.adwords.keywordoptimizer.TrafficEstimate,java.lang.Double
[ERROR] found: com.google.api.ads.adwords.axis.v201603.cm.Keyword,<nulltype>,double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/ben/share/clojure/keyword-optimizer/src/test/java/com/google/api/ads/adwords/keywordoptimizer/KeywordCollectionScoreTest.java:[80,21] incompatible types: com.google.api.ads.adwords.axis.v201603.cm.Money cannot be converted to com.google.api.ads.adwords.axis.v201607.cm.Money

I'm running Ubuntu 15.10.

**Comment by timoboz** [comment]
Thanks for bringing that up, somehow a file (KeywordCollectionScoreTest.java) slipped through the latest update when I bumped the project to v201607 of the AdWords API. Fixed it with the last commit.
